version: '3.1'

services:
  xestor.db.user:
    image: postgres
    container_name: xestor.db.user
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=semog
      - POSTGRES_PASSWORD=Dr4inY0u
      - POSTGRES_DB=user
    volumes:
      - pgdata:/data

  # xestor.api.user.db_push:
  #   build: .
  #   container_name: xestor.api.user.db_push
  #   env_file:
  #     - .env
  #   command: npx prisma db push
  #   volumes:
  #     - .:/usr/xestor.user
  #   depends_on:
  #     - xestor.db.user

  # xestor.api.user:
  #   build: .
  #   container_name: xestor.api.user
  #   env_file:
  #     - .env
  #   command: npm run dev
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   volumes:
  #     - .:/usr/xestor.user
  #   depends_on:
  #     - xestor.db.user
  #     - xestor.api.user.db_push

volumes:
  pgdata:
    driver: local
